export const recipeActionTypes = {
  FETCH_RECIPES: 'FETCH_RECIPES',
  FETCH_RECIPE: 'FETCH_RECIPE',
  RECEIVE_RECIPES: 'RECEIVE_RECIPES',
  RECEIVE_RECIPE: 'RECEIVE_RECIPE',
  CREATE_RECIPE: 'CREATE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  CLEAR_RECIPE_DETAILS: 'CLEAR_RECIPE_DETAILS',
};

export const userActionTypes = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  RESTORE_TOKEN: 'RESTORE_TOKEN',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  FETCH_USER: 'FETCH_USER',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_USERS: 'FETCH_USERS',
  RECEIVE_USERS: 'RECEIVE_USERS',
  RECEIVE_USER: 'RECEIVE_USER',
  RECEIVE_PROFILE: 'RECEIVE_PROFILE',
  CLEAR_USER_DETAILS: 'CLEAR_USER_DETAILS',
};

export const stockActionTypes = {
  FETCH_FOOD_STOCK: 'FETCH_FOOD_STOCK',
  FETCH_STOCK_ITEM: 'FETCH_STOCK_ITEM',
  FETCH_STOCK: 'FETCH_STOCK',
  RECEIVE_FOOD_STOCK: 'RECEIVE_FOOD_STOCK',
  RECEIVE_STOCK_ITEM: 'RECEIVE_STOCK_ITEM',
  RECEIVE_STOCK: 'RECEIVE_STOCK',
  CREATE_STOCK_ITEM: 'CREATE_STOCK',
  UPDATE_STOCK_ITEM: 'UPDATE_STOCK_ITEM',
  DELETE_STOCK_ITEM: 'DELETE_STOCK_ITEM',
  DELETE_STOCK_ITEM_SUCCESS: 'DELETE_STOCK_ITEM_SUCCESS',
  DELETE_STOCK_ITEM_FAIL: 'DELETE_STOCK_ITEM_FAIL',
  CLEAR_STOCK_DETAILS: 'CLEAR_STOCK_DETAILS',
  CLEAR_STOCK_ITEM_DETAILS: 'CLEAR_STOCK_ITEM_DETAILS',
};

export const genericFoodActionTypes = {
  FETCH_FOODS: 'FETCH_FOODS',
  FETCH_FOOD: 'FETCH_FOOD',
  RECEIVE_FOODS: 'RECEIVE_RECIPES',
  RECEIVE_FOOD: 'RECEIVE_RECIPE',
};