export const recipeActionTypes = {
  FETCH_RECIPES: 'FETCH_RECIPES',
  FETCH_RECIPE: 'FETCH_RECIPE',
  RECEIVE_RECIPES: 'RECEIVE_RECIPES',
  RECEIVE_RECIPE: 'RECEIVE_RECIPE',
  CREATE_RECIPE: 'CREATE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
};

export const userActionTypes = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  FETCH_USER: 'FETCH_USER',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_USERS: 'FETCH_USERS',
  RECEIVE_USERS: 'RECEIVE_USERS',
  RECEIVE_USER: 'RECEIVE_USER',
  RECEIVE_PROFILE: 'RECEIVE_PROFILE',
};
