export const recipeActionTypes = {
  FETCH_RECIPES: 'FETCH_RECIPES',
  FETCH_RECIPE: 'FETCH_RECIPE',
  RECEIVE_RECIPES: 'RECEIVE_RECIPES',
  RECEIVE_RECIPE: 'RECEIVE_RECIPE',
  CREATE_RECIPE: 'CREATE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  CLEAR_RECIPE_DETAILS: 'CLEAR_RECIPE_DETAILS',
  FETCH_RECIPE_RECS: 'FETCH_RECIPES_RECS',
  RECEIVE_RECIPE_RECS: 'RECEIVE_RECIPES_RECS',
  FETCH_LIKED_RECIPES: 'FETCH_LIKED_RECIPES',
  RECEIVE_LIKED_RECIPES: 'RECEIVE_LIKED_RECIPES',
};

export const userActionTypes = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  FETCH_USER: 'FETCH_USER',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_USERS: 'FETCH_USERS',
  RECEIVE_USER: 'RECEIVE_USER',
  RECEIVE_PROFILE: 'RECEIVE_PROFILE',
  CLEAR_USER_DETAILS: 'CLEAR_USER_DETAILS',
};

export const stockActionTypes = {
  FETCH_FOOD_STOCK: 'FETCH_FOOD_STOCK',
  FETCH_STOCK_ITEM: 'FETCH_STOCK_ITEM',
  FETCH_STOCK: 'FETCH_STOCK',
  RECEIVE_FOOD_STOCK: 'RECEIVE_FOOD_STOCK',
  RECEIVE_STOCK_ITEM: 'RECEIVE_STOCK_ITEM',
  RECEIVE_STOCK: 'RECEIVE_STOCK',
  CREATE_STOCK_ITEM: 'CREATE_STOCK',
  UPDATE_STOCK_ITEM: 'UPDATE_STOCK_ITEM',
  DELETE_STOCK_ITEM: 'DELETE_STOCK_ITEM',
  DELETE_STOCK_ITEM_SUCCESS: 'DELETE_STOCK_ITEM_SUCCESS',
  DELETE_STOCK_ITEM_FAIL: 'DELETE_STOCK_ITEM_FAIL',
  CLEAR_STOCK_DETAILS: 'CLEAR_STOCK_DETAILS',
  CLEAR_STOCK_ITEM_DETAILS: 'CLEAR_STOCK_ITEM_DETAILS',
  FETCH_RECEIPT_FOODS: 'FETCH_RECEIPT_FOODS',
  RECEIVE_RECEIPT_FOODS: 'RECEIVE_RECEIPT_FOODS',
  FETCH_RECEIPT_FOODS_FAIL: 'FETCH_RECEIPT_FOODS_FAIL',
  DELETE_STOCK: 'DELETE_STOCK',
  DELETE_STOCK_SUCCESS: 'DELETE_STOCK_SUCCESS',
  DELETE_STOCK_FAIL: 'DELETE_STOCK_FAIL',
};

export const genericFoodActionTypes = {
  FETCH_FOODS: 'FETCH_FOODS',
  FETCH_FOOD: 'FETCH_FOOD',
  CLEAR_FOODS: 'CLEAR_FOODS',
  RECEIVE_FOODS: 'RECEIVE_FOODS',
  RECEIVE_FOOD: 'RECEIVE_FOOD',
};

export const searchActionTypes = {
  SEARCH_FOODS: 'SEARCH_FOODS',
  SEARCH_RECIPES: 'SEARCH_RECIPES',
  SEARCH_USERS: 'SEARCH_USERS',
  SEARCH_TAGS: 'SEARCH_TAGS',
  RECEIVE_SEARCH_FOODS: 'RECEIVE_SEARCH_FOODS',
  RECEIVE_SEARCH_RECIPES: 'RECEIVE_SEARCH_RECIPES',
  RECEIVE_SEARCH_USERS: 'RECEIVE_SEARCH_USERS',
  RECEIVE_SEARCH_TAGS: 'RECEIVE_SEARCH_TAGS',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
};
